### ISSUE TITLE
Is there any way you can play a replay?

### ISSUE THREAD

**Issue by andrerpena** [Zednosius/RocketLeagueReplayHandler#2]
Hey. Awesome work. Is there any way you can play a replay without manually entering Rocket League?

**Comment by Zednosius** [comment]
Hi and thanks for the kind words! :)

Currently the only way to play a replay is to do it manually. To do it automatically (which would be nice) Psyonix would basically have to add some kind of flag to the executable so that one could start into replay mode directly by giving it the name/path of a replay.
An alternative would be to make a custom replay viewer, I think i saw someone who had made a very basic viewer (like rectangular shapes driving around)  but I doubt it'd be possible to make something as functional as what exists ingame without spending an inordinate amount of time on it.
But for now we just have to make do with what exists, we can at least avoid some time spent scrolling with the RLRH's staging system :)
